export class GameAudio {
  constructor(settings,onBlocked=()=>{}) {this.settings=settings;this.onBlocked=onBlocked;this.ctx=null;this.voice=null;this.token=0;this.timer=null;this.note=0;this.hidden=false;this.ducked=false;this.nodes=new Set();}
  async unlock() {
    if(this.settings.muted)return;
    try {if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.music=this.ctx.createGain();this.effects=this.ctx.createGain();this.music.connect(this.ctx.destination);this.effects.connect(this.ctx.destination);}
      await this.ctx.resume();this.update(this.settings);this.startMusic();this.onBlocked(this.ctx.state!=='running');
    } catch {this.onBlocked(true);}
  }
  setScene(scene){if(this.scene===scene)return;this.scene=scene;this.note=0;if(this.ctx){const t=this.ctx.currentTime;this.music.gain.cancelScheduledValues(t);this.music.gain.setValueAtTime(0,t);this.music.gain.linearRampToValueAtTime(this.settings.muted?0:this.settings.music*(scene==='camp'?.63:scene==='finale'?.7:1),t+.4);}}
  signal(){for(let i=0;i<3;i++)this.tone(660, .5,this.effects,'sine',.08,0,i*.65);}
  update(settings) {this.settings=settings;const on=!settings.muted&&!this.hidden;if(this.ctx){this.music.gain.setTargetAtTime(on?settings.music*(this.ducked ? .28 : 1):0,this.ctx.currentTime,.15);this.effects.gain.setTargetAtTime(on?settings.sfx*(this.ducked ? .6 : 1):0,this.ctx.currentTime,.05);}if(this.voice){this.voice.volume=settings.voice;this.voice.muted=settings.muted;}if(settings.muted){this.stopVoice();this.onBlocked(false);}}
  tone(freq,duration,bus,type='sine',volume=.045,slide=0,delay=0) {if(!this.ctx || this.settings.muted || this.hidden)return;const t=this.ctx.currentTime+delay,osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,t);if(slide)osc.frequency.exponentialRampToValueAtTime(slide,t+duration);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(volume,t+.012);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(gain);gain.connect(bus);this.nodes.add(osc);osc.onended=()=>{osc.disconnect();gain.disconnect();this.nodes.delete(osc);};osc.start(t);osc.stop(t+duration+.01);}
  sfx(kind) {if(!this.ctx)return;if(kind==='bell'){this.tone(660,.5,this.effects,'sine',.08);return;}if(kind==='open') {this.tone(145,.45,this.effects,'triangle',.09,75);this.tone(350,.1,this.effects,'sine',.04);}else this.tone(210,.22,this.effects,'sine',.12,520);}
  startMusic() {if(this.timer)return;const themes={forest:[392,0,494,440,330,0,392,294,330,0,440,392,294,0,330,262,392,0,523,494,440,0,392,330],home:[262,0,330,392,294,0,349,440,330,0,392,494,349,0,440,523,392,0,330,294,262,0,294,330],shore:[330,392,0,440,392,330,294,0,349,440,0,494,440,349,330,0,392,494,440,392,330,294,262,0]};this.timer=setInterval(()=>{if(this.ctx?.state==='running'&&!this.hidden){const melody=themes[this.scene==='home'||this.scene==='finale'?'home':this.scene==='shore'?'shore':'forest'];const freq=melody[this.note++%melody.length];if(freq)this.tone(freq,1.3,this.music,'sine',.04*(this.scene==='camp'?.63:1));}},1500);}
  stopVoice() {this.token++;if(this.voice){this.voice.pause();this.voice.removeAttribute('src');this.voice.load();this.voice=null;}this.ducked=false;if(this.ctx){this.music.gain.setTargetAtTime(this.settings.muted||this.hidden?0:this.settings.music,this.ctx.currentTime,.15);this.effects.gain.setTargetAtTime(this.settings.muted||this.hidden?0:this.settings.sfx,this.ctx.currentTime,.05);}}
  playVoice(path) {this.stopVoice();if(this.settings.muted||this.hidden||this.available&&!this.available.has(path))return;const token=this.token,voice=new Audio(`./${path}`);this.voice=voice;voice.volume=this.settings.voice;const clear=()=>{if(token!==this.token)return;this.ducked=false;this.update(this.settings);};voice.onended=clear;voice.onerror=clear;voice.onplaying=()=>{if(token!==this.token)return;this.ducked=true;this.update(this.settings);};voice.play().catch(clear);}
  async visibility(hidden) {this.hidden=hidden;this.stopVoice();if(hidden){clearInterval(this.timer);this.timer=null;for(const node of this.nodes){try{node.stop();}catch{}}try{await this.ctx?.suspend();}catch{}}else if(!this.settings.muted){await this.unlock();}}
}
